# Generated by Django 2.1.1 on 2018-09-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='endTime',
            field=models.DateField(null=True),
        ),
    ]
