# Generated by Django 2.1.1 on 2018-09-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
