# Generated by Django 2.1.1 on 2018-09-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20180924_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
